### ISSUE TITLE
Why not just use https://blacklist.salamek.cz/ ?

### ISSUE THREAD

**Issue by Salamek** [CSNOG/MFCR-blacklist#2]
* It automaticaly parses PDF's
* It have REST JSON API
* It shows list of blocked domains with screenshoots, redirect destinations, ip...
* It shows all PDF's with stats and sha256 sum
* It is fully OSS https://github.com/Salamek/blacklist
* Provides deb and archlinux installation packages for enyone who wants to run it on their own server
....

**Comment by oskar456** [comment]
In my opinion, it's too complex solution with too many moving parts. The point here is that anybody can simply check that the list is on par with the PDF list, people can subscribe to commits and get e-mail notifications, etc.

Nevertheless, feel free to submit a PR to the README file, listing your website as an alternative solution.

**Comment by Salamek** [comment]
@oskar456 

> The point here is that anybody can simply check that the list is on par with the PDF list

You can do that there too...

> e-mail notifications

Email ? Ou... i rather had webhooks or something...

If you wish to do things manually... it's your time :-)
