### ISSUE TITLE
Add SUKL blocklist?

### ISSUE THREAD

**Issue by analogic** [CSNOG/MFCR-blacklist#4]
Thanks for your work!

It is empty now but format seems to be almost same as MFCR's machine processable pdf™

https://www.sukl.cz/farmaceuticky-prumysl/seznam-stranek-s-nelegalni-nabidkou-lecivych-pripravku

**Comment by oskar456** [comment]
Oh my… They don't even have RSS. I have no Idea how to figure out the list has changed. But in general, I'm in. If there's anyone willing to maintain the list, that would be nice.

**Comment by analogic** [comment]
Well it turned out better then expected. SÚKL has actually made data truly machine processable. Here is one liner for anyone interested

```wget -q https://opendata.sukl.cz/soubory/NELEGALNI_STRANKY/Nelegalni_stranky_LP.csv -O - | tail -n +2 | awk -F"," '{print $1}' | awk '{print substr($0, 2, length($0) - 2)}'```

Closing!

**Comment by oskar456** [comment]
I think we can set up a repository to download and archive the lists. It could work automatically using GitHub Actions. Any volunteers? :)

**Comment by analogic** [comment]
Might be possible. I try to look into it in near non-distant future as good self-intro to Actions (more of Drone CI guy right now)
