### ISSUE TITLE
https://github.com/analogic/cz-gov-blocks a v68

### ISSUE THREAD

**Issue by analogic** [CSNOG/MFCR-blacklist#5]
Podle MFCR uz je verze 68

A shameless plug - https://github.com/analogic/cz-gov-blocks obsahuje vsechny tri block listy (MFCR, SUKL, USKVBL) + dezinfo, je to cele automatizovano via github actions

**Comment by oskar456** [comment]
Díky, přidal jsem do README a taky přidal poznámku o nedůvěryhodnosti tohoto repozitáře.
